apiVersion: v1
kind: ConfigMap
metadata:
  name: simplewatch-config
  namespace: simplewatch
data:
  APP_NAME: "SimpleWatch Production"
  CHECK_INTERVAL: "60"
  DB_HOST: "mysql-service"
  DB_NAME: "simplewatch"
  DB_USER: "simplewatch"
