apiVersion: v1
kind: Service
metadata:
  name: simplewatch-service
  namespace: simplewatch
spec:
  type: LoadBalancer  # ← AWS ELB oluşturur
  selector:
    app: simplewatch-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
